In [2]:
import json
import chromadb
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from chromadb.config import Settings

In [3]:
def json_to_chunks(docs):
    all_chunks = []
    example_key = next(iter(docs))
    record_ids = docs[example_key].keys()  

    for record_id in record_ids:
        chunk = {}
        for key in docs:
            # Skip if the key is duplicated like 'Name', 'Name', etc.
            if key not in chunk:  
                chunk[key] = docs[key].get(record_id)
        all_chunks.append(chunk)

    return all_chunks

In [4]:
def load_and_merge_json(path):
    all_chunks = []
    for filename in os.listdir(path):
        if filename.endswith('.json'):
            with open(os.path.join(path, filename),'r', encoding='utf-8') as f:
                data = json.load(f)
                all_chunks.extend(json_to_chunks(data))
                break
    return all_chunks

In [11]:
uni_chunks=[]
with open("/Users/nitinchaube/Studies/IMPS/ALLAboutAI/Project/AdvisorAI/AdvisorAI/Backend/Data/AllFacultyResearchInformaion.json",'r', encoding='utf-8') as f:
    data = json.load(f)
    uni_chunks.extend(json_to_chunks(data))

In [12]:
uni_df = pd.DataFrame(uni_chunks)

In [13]:
uni_df.head()

                                 FacultyResearchInfo
0  Aleksi Aaltonen 0 I study data-based organizin...
1                                 Cherif Amirat 1
2  Richard Anderson 2 Anderson, Richard; Grossman...
3  Eunkyung An 3 Quantitative Marketing Online/Mo...
4  Zvi Aronson 4 Project and team performance: th...

In [14]:
records = uni_df.to_dict(orient="records")

In [15]:
with open("./Data/AllFacultyResearchInformation.json", "w", encoding="utf-8") as f:
    json.dump(records, f, indent=2, ensure_ascii=False)

In [118]:
all_chunks = load_and_merge_json("./Data/")

In [119]:
all_chunks

[{'FacultyGeneralInfo': 'Aleksi Aaltonen Academics https://www.stevens.edu/profile/aaaltone  (201) 216-5423 [email\xa0protected] Website PhD (2012) The London School of Economics and Political Science (Information Systems) MS (2005) University of Helsinki (Sociology) Before joining academia, I designed and built digital services for organizations such Nokia and CMI – Martti Ahtisaari Peace Foundation founded by Nobel Peace Laureate and former President of Finland Martti Ahtisaari. After completing my PhD at the London School of Economics and Political Science, I cofounded and helped to raise 1.7 million euros funding for an activity tracking app Moves. Apple chose Moves as the Best App of 2013 in the Fitness Revolution category, and the company was acquired by Facebook in April 2014. Associate Professor, Stevens Institute of Technology, NJ, 2024– Assistant Professor, Fox School of Business, Temple University, PA, 2018–2024 Assistant Professor, Warwick Business School, UK, 2014–2018 Deputy Editor-in-Chief, Journal of Information Technology, January 2025– MIS110 Creative Problem Solving in Programming BT416 Business Process Management'},
 {'FacultyGeneralInfo': 'Cherif Amirat Academics https://www.stevens.edu/profile/camirat Altorfer 404 (201) 216-8642 [email\xa0protected] Website Other (2003) Harvard (Pfizer Leadership Program) MBA (1996) Wharton Business School, University of Pennsylvania (Managment) PhD (1988) Stevens Institute of Technology (Electrical Engineering and Computer Science) MS (1984) Stevens Institute of Technology (MEE Electrical Engineering and Computer Science) BE (1981) INELEC (Electonics and Electrical Engineering)    '},
 {'FacultyGeneralInfo': 'Richard Anderson Academics https://www.stevens.edu/profile/randers2 Altorfer 515C (201) 216-8935 [email\xa0protected]      '},
 {'FacultyGeneralInfo': 'Eunkyung An Academics https://www.stevens.edu/profile/ean2 Altorfer 515A (201) 216-5425 [email\xa0protected] Website PhD (2024) New York University (Marketing) MA (2017) Columbia University (Quantitative Methods in Social Sciences) BS (2015) Ulsan National Institute of Science and Technology (Human Factors Engineering)    BIA672 Marketing Analytics'},
 {'FacultyGeneralInfo': 'Zvi Aronson Academics https://www.stevens.edu/profile/zaronson Babbio Center 418 (201) 216-5032 [email\xa0protected]  PhD (1998) Stevens Institute of Technology (Applied Psychology) BA (1984) Ben Gurion University, Israel (Behavioral Sciences \t) Zvi H. Aronson has developed and taught courses in the human side of project leadership, organizational behavior and change and development. Zvi has two areas of research. One area relates to the role of personal style in project leader and team performance. The other area of research is project culture and the role that it plays in project success. His work appears in several journals including, R & D Management, the International Journal of Selection and Assessment, Project Management Journal, the Journal of Engineering and Technology Management, and in several book chapters. Zvi also serves as a reviewer for several TIM journals, including R & D Management. Prior to joining Stevens faculty, he was employed at Bakara Ltd., Israel, where he conducted research in the areas of training and selection, and provided software instruction to clients. Editorial Board - IEEE Transactions on Engineering Management - ABS Level 3 Journal Editorial Board - IEEE Transactions on Engineering Management - ABS Level 3 Journal '},
 {'FacultyGeneralInfo': 'Christopher Asakiewicz Academics https://www.stevens.edu/profile/casakiew Babbio Center 427 (201) 216-8012 [email\xa0protected] Website PhD (2003) Stevens Institute (Information Management) MS (1983) Stevens Institute (Electrical Engineering) BS (1977) Columbia University (Electrical Engineering and Computer Science) Publications and Speaking Engagements: Journal Articles: Building a Cognitive Application using Watson DeepQA, Accepted for Publication July/August 2017, IEEE IT Professional Magazine. Translational Research 2.0 – A Framework for Accelerating Collaborative Discovery, May 2014, Journal of Personalized Medicine, Volume 11, Number 3, pp 351-358. Business Investments in IT: Managing Integration Risk, July/August 2011, IEEE IT Professional Magazine. Conference Proceedings: Accelerating Translational Research by Leveraging AI and Machine Learning, PhUSE 2020 US Connect Conference, Orlando, Florida, at: https://www.phusewiki.org/docs/2020%20US%20Connect%20Florida/Presentations/ML/Final%20Papers/ML04%20pdf.pdf The Impact of Data and Knowledge Integration on Biobanking and Collaborative Discovery, 2010, International Conference on Management Science and Information Engineering (ICMSIE) Semantic Discovery in Biomedical Research: Grants, Patents, and Publications, 2010, International Conference on Cellular, Molecular Biology, Biophysics and Bioengineering (CMBB) Doubling IT Innovation Spending: Laying the Foundation for IT-Enabled Business Process, Supply Chain, and Service Innovation in the Pharmaceutical Industry, 2009, International Conference on Management and Service Science, Beijing, China, IEEE Catalog Number: CFP0941H-CDR, ISBN: 978-1-4244-4639-1 White Papers: Cognitive Analytics for Making Better Evidence-based Decisions, 2017, SSRN Available at: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2965767. The Intelligent Enterprise: Scenario Analysis for Better Decision Making in Pharmaceutical, Diagnostic, and Medical Device New Product Development, 2015 Translational Research 2.0 – Searching for Answers in a World of Big Data, SSRN 2013 Translational Research 2.0, 2012 Integrated Research Systems – Accelerating Medical and Healthcare Research, 2011. Research Monograph: Enterprise Systems Value-Based R&D Portfolio Analytics: Methods, Processes, and Tools, 2014, A013 – Final Technical Report , Systems Engineering Research Center, SERC-2014-RT-041-1 Keynote/Major Speaker Engagements: AI Enabled Collaboration – Opportunities and Implications in these Times of COVID, PhUSE Conference “Moving Forward After the Global Pandemic” Keynote Presentation, July 2022 The Language of Business in Pharmaceutical and Life Science Research, Pfizer Worldwide Research and Development “The Business of Science” Invited Webinar Series, March 2021. Accelerating Translational Research by Leveraging AI and Machine Learning, PhUSE 2020 US Connect Conference, Orlando, Florida, at: https://www.youtube.com/watch?v=7Vurg4_CvvM&list=PLS6XDiRNQo00BYx8nyJkll8BRfjPP3zSR&index=4&t=0s Industry Academic Partnership (Genesis Research and Stevens School of Business), PhUSE Conference “Artificial Intelligence and the Digital Transformation of Healthcare” Keynote Presentation and Conference Chair, July 2019 Cognitive Analytics for Enhanced Data Analysis and Decision Making, PhUSE Conference “Artificial Intelligence and Data Automation – Game Changer on Data Analysis and Decision Making” Invited Presentation, May 2018 Cognitive Analytics for Making Better Evidence-based Decisions, PhUSE Conference “The Future is Now – Harnessing Big Data!” Invited Presentation, August 2017 The Language of Business in Pharmaceutical and Life Science Research, Pfizer Worldwide Research and Development “The Business of Science” Invited Lecture, August 2016 High Velocity Organizations, HSATM Roundtable, July 2015 The Intelligent Enterprise: Scenario Analysis for Better Decision Making, HSATM Research Forum, November 2014 Translational Research 2.0, Cambridge Health Technology Web Symposium, September 2012 Integrated Research Systems – Accelerating Medical and Healthcare Research, Research Informatics Web Conference, August, 2011 The Impact of Data and Knowledge Integration on Biobanking and Collaborative Discovery, International Society of Biological and Environmental Repositories (ISBER) 2010 Annual Meeting, May 11th – May 14th, 2010 Rotterdam, Netherlands Semantic Discovery in Biospecimen Science, 3rd Annual Biospecimen Research Network (BRN) March 24th – March 25th, 2010. Bethesda, Maryland Keynote: IT-Enabled Process Integration Risk Management and its Impact on Biomedical Research, Bio IT World Expo Europe: October 6th – October 9th, 2009 – Hannover, Germany Keynote: Doubling IT Innovation Spending: Laying the Foundation for IT-Enabled Business Process, Supply Chain, and Service Innovation in the Pharmaceutical Industry, Bridging IT and Pharma Conference: September 30th – October 2nd, 2007 - Hyatt Harborside - Boston, MA Keynote: Maximizing the Business Value of IT, Wharton Technology Conference, Philadelphia, PA, 2004 e-Seminar: Knowledge Mining: Fast and Effective Analysis of Clinical Research Results, ClearForest e-Seminar Series, 2004 Colloquia: Implementing IT Governance, Carnegie Mellon University, Tepper School of Business, 2004 A senior management professional with strategic background in Business Technology Management, Information Technology, Consulting and Education with a 21-year history as a Vice President of Global Business Technology at Pfizer.  Chris has done pioneering work in the areas of Knowledge Mining and its application within Life Sciences, most notably as a means of accelerating Translational Research.  His research and teaching interests include: Cognitive Systems; Healthcare Analytics; Enterprise-level Application; Information; and Business Process Rationalization; as well as Talent, Skill, and Capability Development.  BIA 686 Applied Analytics MIS 690 Strategic Supply Chain Management BIA 662 Cognitive Computing MIS 636 Data Integration and Business Intelligence'},
 {'FacultyGeneralInfo': 'Suman Banerjee Academics https://www.stevens.edu/profile/sbanerj2 Babbio Center 638 (201) 216-3689 [email\xa0protected]      '},
 {'FacultyGeneralInfo': 'Tal Ben-Zvi Academics https://www.stevens.edu/profile/tbenzvi Babbio Center 416 (201) 216-8545 [email\xa0protected]   Government and Public Service 1995-2000 Israeli Army Service (Lieutenant) 1998-2000 Budget Department, Israel Ministry of Defense Associate Professor, Stevens Institute of Technology, Hoboken, NJ (2013-present) Director of the Project Management Program, Stevens Institute of Technology, Hoboken, NJ (2013-2015) Assistant Professor, Stevens Institute of Technology, Hoboken, NJ (2006-2013) Teacher, Faculty of Management, The Leon Recanati Graduate school of Business Administration, Tel Aviv University (2002-2006) Adjunct Lecturer, Academic College of Tel-Aviv-Yaffo (2003-2006) Adjunct Lecturer, College of Management (2004-2005) Adjunct Lecturer, Kellogg School of Management, Northwestern University – Recanati Graduate School of Business Administration, Tel-Aviv University: A joint High-Tech MBA Program (2004) Teaching Assistant, Academic College of Tel-Aviv-Yaffo (2000-2005) Teaching Assistant, College of Management (2000-2002) Teaching Assistant, Kellogg School of Management, Northwestern University – Recanati Graduate School of Business Administration, Tel-Aviv University: A joint MBA Program (2000) Teaching Assistant, Faculty of Management, The Leon Recanati Graduate school of Business Administration, Tel Aviv University (1999-2002)  '},
 {'FacultyGeneralInfo': 'James Biagi Academics https://www.stevens.edu/profile/jbiagi Babbio Center 424 (201) 216-5035 [email\xa0protected]  JD (1990) State University of New York at Buffalo School of Law (Tax Law) BBA (1986) Pace University (Accounting) Attorney in the State of New York (1991) and admitted to practice before the United States Tax Court and Southern District of New York. Certified Public Accountant licensed in the State of New York since 1990. Former law firm partner and practicing Tax Attorney Former Trial Attorney with the Office of Chief Counsel for the Internal Revenue Service Former Auditor with EY  ACC-351: Federal Taxation of Individuals ACC-352: Federal Taxation of Business Entities ACC-431: Advanced Accounting ACC-552: Tax Compliance and Planning for Business Entities ACC-585: Fraud Examination and Forensic Investigation FIN-500: Financial & Managerial Accounting'},
 {'FacultyGeneralInfo': 'Stefano Bonini Academics https://www.stevens.edu/profile/sbonini Babbio Center 425 (201) 216-3528 [email\xa0protected] Website   New York University, Stern School of Business, Visiting Associate Professor of Finance: 2009;2012-2013 Bocconi University, Department of Finance, Assistant Professor, 2005-2014 Fudan University (Shanghai, PRC) Adjunct Professor, 2006-2011 Visiting Fellow, Harvard University/MIT, Department of Economics, Cambridge, MA 1999  '},
 {'FacultyGeneralInfo': 'Dragos Bozdog Academics https://www.stevens.edu/profile/dbozdog Babbio Center 609 (201) 216-3527 [email\xa0protected]  PhD (2014) Stevens Institute of Technology (Financial Engineering) PhD (2005) University of Toledo (Mechanical Engineering) BS (1997) Polytechnic University of Bucharest (Mechanical Engineering) Dragos Bozdog is a Teaching Associate Professor of Financial Engineering at School of Business and Deputy Director of The Hanlon Financial Systems Laboratories. His research interests include Multivariate Methods for Rare Events Analysis of High-Frequency Financial Data, Machine Learning in Finance, Early Warning Systems and Threat Assessment. He worked as quantitative analysts in high-frequency trading in the financial industry and government. His research was presented at domestic and international conferences and he publishes regularly in journals. He has extensive teaching experience in Financial Engineering, Financial Analytics, Business Intelligence and Analytics, Quantitative Finance and Mathematics at graduate and undergraduate level. Prior joining Stevens, he was a Post-Doctoral Fellow at Rutgers Center for Operations Research where he worked on Logical Analysis of Data Models. He is a member of The International Association for Quantitative Finance (IAQF) and The Scientific Research Society (Sigma Xi). He has a Ph.D. in Financial Engineering from Stevens Institute of Technology and a Ph.D. in Mechanical Engineering from The University of Toledo. 2015 - Present: Teaching Associate Professor in Financial Engineering , Stevens Institute of Technology, Hoboken, NJ 2015 - Present: Deputy Director, Hanlon Financial Systems Laboratories, Stevens Institute of Technology, Hoboken, NJ 2012 - 2015: Adjunct Professor in Financial Engineering , Stevens Institute of Technology, Hoboken, NJ 2005 – 2006: Post-Doctoral Fellow , Rutgers Center for Operations Research (RUTCOR), Rutgers, The State University of New Jersey, Piscataway, NJ  FE-900 - Thesis in Financial Engineering FE-680 - Advanced Derivatives FE-630 - Portfolio Theory and Applications FE-621 - Computational Methods in Finance FE-620 - Pricing and Hedging FE-540 - Probability Theory for Financial Engineering FE-530 - Introduction to Financial Engineering FE-518 - Financial Lab: Mathematica for Finance FE-517 - Financial Lab: SAS for Finance FE-511 - Financial Lab: Introduction to Bloomberg and Thomson Reuters FA-582 - Foundations of Financial Data Science FA-542 - Time Series with Applications to Finance FA-541 - Applied Statistics with Applications to Finance QF-103 - Financial Lab: Introduction to Financial Tools and Technology BIA-656 - Advanced Data Analytics and Machine Learning BT-243 - Macroeconomics MA-331 - Intermediate Statistics MA-221 - Differential Equations CS-110 - Creative Problem Solving in Computing'},
 {'FacultyGeneralInfo': 'Jing Chen Academics https://www.stevens.edu/profile/jchen4 Babbio Center 414 (201) 216-8062 [email\xa0protected] Website PhD (2014) New York University (Accounting) BBA (2009) Renmin University of China (Accounting)  Associate Professor of Accounting, School of Business, Stevens Institute of Technology, 2024 - Present Assistant Professor of Accounting, School of Business, Stevens Institute of Technology, 2019 - 2024 Assistant Professor of Accounting, School of Management, University at Buffalo, SUNY, 2014 - 2019  ACC 215 Managerial Accounting ACC/FIN 510 Financial Statement Analysis ACC 311 Intermediate Accounting I (before 2023)'},
 {'FacultyGeneralInfo': 'Violet Chen Academics https://www.stevens.edu/profile/vchen3 Babbio Center 646 (201) 216-3521 [email\xa0protected] Website PhD (2022) Carnegie Mellon University (Operations Research) BS (2017) Georgia Institute of Technology (Applied Mathematics; Business Administration)    MIS637 - Data Analytics and Machine Learning'},
 {'FacultyGeneralInfo': "Arion Cheong Academics https://www.stevens.edu/profile/acheong Altorfer 415E (201) 216-3640 [email\xa0protected] Website PhD (2021) Rutgers University (Accounting Information Systems) MA (2017) University of Texas at Austin (Economics) BA (2015) Kyunghee University (International Studies) Arion's research focuses on automating auditing through big data and AI, cybersecurity assurance and reporting, and the managerial implications of information technology. He has advised organizations on the adoption of audit data analytics, including the Brazilian Stock Exchange (B3) and AB InBev.   "},
 {'FacultyGeneralInfo': 'Zhenyu Cui Academics https://www.stevens.edu/profile/zcui6 Babbio Center 545 (201) 216-3726 [email\xa0protected] Website PhD (2013) University of Waterloo (Statistics) MS (2010) University of Waterloo (Quantitative Finance) BS (2008) University of Hong Kong (Actuarial Science) Dr. Cui is an Associate Professor of Financial Engineering at the School of Business at Stevens Institute of Technology. He holds a BS (with first class honors) in Actuarial Science from the University of Hong Kong, a master in quantitative finance, and a PhD in statistics from the University of Waterloo. His research lies in financial engineering, insurance analytics and operations research. His research has been published at leading journals including Mathematical Finance, Finance and Stochastics, SIAM Journal on Financial Mathematics, Econometric Theory, European Journal of Operational Research, Journal of Economic Theory, Journal of Financial Econometrics, Insurance: Mathematics and Economics, and INFORMs Journal on Computing. He is member of the Society of Actuaries and the Society of Financial Econometrics. SSRN: http://ssrn.com/author=1276571 ResearchGate: https://www.researchgate.net/profile/Zhenyu_Cui Google Scholar: http://scholar.google.com.sg/citations?user=pW68lnMAAAAJ Associate Professor, Financial Engineering, Stevens Institute of Technology. Sep. 2022 - now Assistant Professor, Financial Engineering, Stevens Institute of Technology. Aug. 2015 - August 2022 Assistant Professor, Department of Mathematics, Brooklyn College of the City University of New York. Aug. 2013-July. 2015  FE 540 Probability Theory for Financial Engineering FA-541 Applied Statistics with Applications to Finance FE 610 Stochastic Calculus for Financial Engineers FE-621 Computational Methods in Finance FE-646 Optimization Models and Methods in Finance FE-710 Applied stochastic differential equations FE-720 Volatility surface: risk and models FE-800 Project in Financial Engineering FA-800 Project in Financial Analytics FE-900 Master Thesis in Financial Engineering FE 960 Ph.D. Research Topic MGT 960 Research in Management'},

In [120]:
len(all_chunks)

3233

In [124]:
all_chunks[3000]

{'FacultyResearchInfo': 'Eduardo Bonelli 16 Foundations of programming languages including the following areas of interest: Lambda Calculus, Type Theory, Proof Theory, Rewriting Theory. 2023 Distinguished Teaching Faculty, Student Government Association. Recipient of the 2022 SAA Outstanding Teacher Award, Stevens Alumni Association Board of Directors. 2019 Alexander Crombie Humphreys Distinguished Teaching Associate Professor Award. '}

In [109]:
from nltk.tokenize import word_tokenize
def get_max_token_length(chunks):
    max_length = 0
    longest_chunk = None
    for chunk in chunks:
        combined_text = " ".join(str(value) for value in chunk.values() if value)
        tokens = word_tokenize(combined_text)
        length = len(tokens)
        if length > max_length:
            max_length = length
            longest_chunk = chunk
    return max_length, longest_chunk

In [110]:
get_max_token_length(all_chunks)

(6689,

In [111]:
df = pd.DataFrame(all_chunks)

In [112]:
df.head()

,FacultyGeneralInfo,Course Code,Course Title,Course URL,Course Name,Course Number,Course Description,Credits,Course Professor,Course Prerequisite,...,school/degrees_awarded/predominant_recoded,school/tuition_revenue_per_fte,school/instructional_expenditure_per_fte,school/institutional_characteristics/level,location/lat,location/lon,id,ope6_id,ope8_id,fed_sch_cd
0,Aleksi Aaltonen | Academics | https://www.stev...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cherif Amirat | Academics | https://www.steven...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Richard Anderson | Academics | https://www.ste...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Eunkyung An | Academics | https://www.stevens....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Zvi Aronson | Academics | https://www.stevens....,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df1 = pd.read_json("./Data/AllFacultyGeneralInformation.json")
df2 = pd.read_csv(".//Data/AllFacultyResearchInformaion.json")

In [19]:
from collections import deque

In [20]:
class Solution:
    def __init__(self):
        self.coordinates = [
            [-1, -2], [-1, 2], [1, 2], [1, -2],
            [-2, -1], [-2, 1], [2, -1], [2, 1]
        ]
    def dfs_helper(self, src_x, src_y, tar_x, tar_y, n):
        visited =[[0 for _ in range(n)] for _ in range(n)]
        q = deque()
        q.append((src_x, src_y))
        visited[src_x][src_y] = 1
        steps = 0
        while q:
            q_size = len(q)
            while q_size>0:
                x, y = q.popleft()
                if x==tar_x and y==tar_y:
                    return steps
                
                for x1, y1 in self.coordinates:
                    new_x, new_y = x+x1, y+y1
                    if 0<=new_x<n and 0<=new_y<n and visited[new_x][new_y] == 0:
                        visited[new_x][new_y] = 1
                        q.append((new_x, new_y))

                q_size-=1
            steps+=1


        return -1



    def MinimumKnightMoves(self, source, target, n):
        src_x = n - source[1]
        src_y = source[0] - 1
        tar_x = n - target[1]
        tar_y = target[0] - 1
        return self.dfs_helper(src_x, src_y, tar_x, tar_y, n)

In [21]:
finder = Solution()
KnightPos = [4, 5]
TargetPos = [1, 1]
n = 6
print(finder.MinimumKnightMoves(KnightPos, TargetPos, n))

3